FROM node:14-alpine3.12
WORKDIR /workspace
COPY package.json .
RUN npm install && \
    npm install --save react-router-dom@5.2.0 && \
    npm install --save axios@0.21.0 && \
    npm install --save react@17.0.1 && \
    npm install --save react-dom@17.0.1 && \
    npm install --save react-scripts@4.0.1 && \
    npm install --save web-vitals@0.2.4 && \
    npm install --save react-router-dom@5.2.0 && \
    npm install --save node-sass@4.14.0 && \
    npm install --save rebuild node-sass &&\
    npm install --save react-cookie@4.0.3 && \
    npm install --save react-validation@3.0.7 && \
    npm install --save validator@13.0.0
