#https://saasitive.com/tutorial/docker-compose-django-react-nginx-let-s-encrypt/
version: "3"

services:
 db:
   image: postgres
   environment:
     - POSTGRES_DB=${DB_NAME}
     - POSTGRES_USER=${DB_USER}
     - POSTGRES_PASSWORD=${DB_PASSWORD}
   ports:
     - ${DB_PORT}

 backend:
   build: "./backend/Docker"
   ports:
     - "8000:8000"
   volumes:
     - ./backend:/workspace

   command:
      bash -c "python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn sound_create.wsgi --bind 0.0.0.0:8000"

   depends_on:
     - db

 frontend:
   build: "./frontend/Docker"
   volumes:
     -  ./frontend:/workspace
     -  /workspace/node_modules
   ports:
     - "3000:3000"
   command: yarn build
#   command: npm start
   depends_on:
     - backend

 nginx:
   image: nginx:latest
   ports:
     - "80:80"
   volumes:
     -  ./nginx/:/etc/nginx/conf.d/
     -  ./frontend/build:/var/www
   depends_on:
     - backend
     - frontend
