version: "3.7"

services:
 db:
   image: postgres
   environment:
     - POSTGRES_DB=${DB_NAME}
     - POSTGRES_USER=${DB_USER}
     - POSTGRES_PASSWORD=${DB_PASSWORD}
   ports:
     - ${DB_PORT}

 backend:
   build:
     context: .
     dockerfile: ./DockerfileBackend
   volumes:
     - staticfiles:/staticfiles
     - mediafiles:/mediafiles
   ports:
     - "8000:8000"
   depends_on:
     - db

 frontend:
   build:
     context: ./frontend/Docker/
     dockerfile: DockerfileFrontend
   volumes:
     -  ./frontend:/dockerFrontend
     -  /dockerFrontend/node_modules
     -  build_folder:/dockerFrontend/build
   command: yarn build
   ports:
     - "3000:3000"

 nginx:
   build:
     context: ./nginx/
     dockerfile: DockerfileNginx
   volumes:
     - build_folder:/var/www/
     - staticfiles:/staticfiles
     - mediafiles:/mediafiles
   ports:
     - "80:80"
   depends_on:
     - backend
     - frontend

volumes:
  build_folder:
  staticfiles:
  mediafiles:
