version: "3.7"

services:
 backend:
   build:
     context: .
     dockerfile: ./DockerfileBackend
   volumes:
     - staticfiles:/staticfiles
     - media:/media
   ports:
     - "8000:8000"

 frontend:
   build:
     context: ./frontend/Docker/
     dockerfile: DockerfileFrontend
   volumes:
     -  ./frontend:/dockerFrontend
     -  /dockerFrontend/node_modules
     -  build_folder:/dockerFrontend/build
   command: yarn build
   ports:
     - "3000:3000"

 nginx:
   build:
     context: ./nginx/
     dockerfile: DockerfileNginx
   volumes:
     -  build_folder:/var/www/
     -  staticfiles:/staticfiles
     -  media:/media
   ports:
     - "80:80"
   depends_on:
     - backend
     - frontend

volumes:
  build_folder:
  staticfiles:
  media:
